version: '3.7'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    container_name: repair-devel-php
    volumes:
      - ./.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    networks:
      - yii2

  mysql:
    image: mysql:8.0
    container_name: repair-devel-db
    restart: unless-stopped
    tty: true
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      MYSQL_DATABASE: repair-devel-db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - repair-devel-db-data:/var/lib/mysql
    networks:
      - yii2

  test-mysql:
    image: mysql:8.0
    container_name: repair-test-db
    restart: unless-stopped
    tty: true
    ports:
      - '3307:3306'
    expose:
      - '3307'
    environment:
      MYSQL_DATABASE: repair-test-db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - repair-test-db-data:/var/lib/mysql
    networks:
      - yii2

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0
    container_name: repair-devel-admin
    restart: unless-stopped
    depends_on:
      - mysql
      - test-mysql
    environment:
      PMA_HOSTS: mysql,test-mysql
    ports:
      - '8884:80'
    links:
      - mysql
      - test-mysql
    networks:
      - yii2

volumes:
  repair-devel-db-data:
  repair-test-db-data:

networks:
  yii2:
